### ISSUE TITLE
Run on device failed

### ISSUE THREAD

**Issue by JeromeTW** [BiAtoms/SQLite.viewer#1]
Xcode 10 Swift 3
![2018-11-06 3 43 47](https://user-images.githubusercontent.com/11555237/48049811-d35ce200-e1da-11e8-9cd7-a84409be6516.png)

**Comment by OrkhanAlikhanov** [comment]
Hey! What is the issue? It seems build failed nothing to do width device.

**Comment by JeromeTW** [comment]
In my case,
I need to use
` pod 'SQLite.viewer', '~> 2.1.0', :configurations => ['Debug']`
   
 not
    `pod 'SQLite.viewer', '~> 1.0', :configurations => ['Debug']`

Thank you @OrkhanAlikhanov !!

**Comment by JeromeTW** [comment]
@OrkhanAlikhanov Could you update ReadME for others? Thanks~
